### ISSUE TITLE
Missing discussion of previously prepared graphs in manuscript

### ISSUE THREAD

**Issue by cthoyt** [OpenBioLink/OpenBioLink#10] opened 2020-01-07 15:20 UTC
The manuscript describes the creation of a new biomedical knowledge graph to use as a benchmark for link prediction. One of the first questions I had was the manuscript did not discuss previously prepared biomedical knowledge graphs. 

The knowledge graph embedding community already uses UMLS as a benchmark dataset. I don't think it's such a good one, and it would be a great opportunity for you to get a word in on why this might be the case (I'd love to hear your opinions). There's also the huge graph available though Bio2RDF, but I'm also not a big fan of this because it's more of an RDF project than an interpretable network.

I think @dhimmel may have been too modest as a reviewer (or just plain fair, since it is his own work) but the real point I wanted to get to was to ask why not just turn Hetionet into *the* gold standard benchmark biomedical knowledge graph? It is incredibly comprehensive and is prepared in a way that it's already ready for use in link prediction (in fact, we're doing just that on https://github.com/drugrelink/ if you're interested to see a use case).

As one of the developers of PyKEEN, I know a practical problem with using knowledge graph embeddings for link predictions is scaling to bigger graphs. Maybe this is an issue you would have with Hetionet. FYI, we're working on that with a new version of PyKEEN that's much more efficient with training, but I also understand that your package isn't specifically tied to one link prediction library or another.

Counterpoint: having a smaller biomedical knowledge graph that is still challenging (i.e., IMO algorithms aren't already scoring above .9 on metrics like ROC-AUC) seems like a great thing. If you can prepare a new network that's 15K nodes instead of 500K, then I am also a supporter! 

I would be interested to hear your thoughts and get a bit more insight into why you chose to construct the network the way you did. I hope that kind of discussion could also make it into the manuscript

**Comment by dhimmel** [comment] 2020-01-07 18:33
> I wanted to get to was to ask why not just turn Hetionet into the gold standard benchmark biomedical knowledge graph?

I'd certainly be interested in this application of Hetionet. I could also imagine a situation where it would be helpful to have multiple networks for benchmarking. For example, if the authors wanted to run a challenge where testing performance would be evaluated on a previously undisclosed testing set.

With the right amount of modularity in the OpenBioLinks code and standardized network IO formats, perhaps it would be very little extra work to split hetionet into train-test labeled edge sets. This would help establish OpenBioLinks as not only a network or benchmark but also a software tool to create train-test partitions for edge prediction. This application is most novel aspect of the study IMO.

> I would be interested to hear your thoughts and get a bit more insight into why you chose to construct the network the way you did. I hope that kind of discussion could also make it into the manuscript

Agreed, but given the 2 page limit, I think it's fine to reference a supplement or documentation page with the actual description.

**Comment by matthias-samwald** [comment] 2020-01-09 11:32
`The manuscript describes the creation of a new biomedical knowledge graph to use as a benchmark for link prediction. One of the first questions I had was the manuscript did not discuss previously prepared biomedical knowledge graphs.`

The list of desirable properties for such a benchmark listed in the manuscript is the driving motivation. The benchmark dataset should fulfill the listed criteria and should be optimized for the link prediction task. For example, the triples in Bio2RDF also contain a lot of metadata triples that would  distort any resulting graph embedding and would need to be filtered out. UMLS is mostly a terminological resource and has licensing restrictions. We also wanted a resource where the whole pipeline of graph creation, train-test-splitting and evaluation is reproducible, transparent and easily modifiable.

**Comment by matthias-samwald** [comment] 2020-01-09 11:45
`Counterpoint: having a smaller biomedical knowledge graph that is still challenging (i.e., IMO algorithms aren't already scoring above .9 on metrics like ROC-AUC) seems like a great thing. If you can prepare a new network that's 15K nodes instead of 500K, then I am also a supporter!`

Indeed, but we feel drawn to the idea of being able to train and test state-of-the-art algorithms on the totality of openly available biomedical knowledge :) 
I'd rather tend to think big and grow OpenBioLink with further types of nodes and relations, as well as enriching it with node attributes (which can be used by some algorithms). Synergizing with the Hetionet project would certainly also be a top priority here!

**Comment by matthias-samwald** [comment] 2020-02-13 13:16
→ We removed the bullet list from the introduction (and moved it to the ReadMe of the GitHub repo). 

Updated text in the introduction section:

“Unfortunately, these benchmarks are often found to have flaws such as information leakage between train- and test-sets (\cite{Toutanova2015}) and do not reflect the domain-specific properties of heterogeneous biomedical knowledge bases. Instead of capturing primarily knowledge networks (FB15K) or hierarchical taxonomies (WN18, UMLS), biomedical knowledge bases often combine richly structured ontological hierarchies with large interaction networks. Predictions of interest usually cannot be made based on simple, crisp rules. Biomedical knowledge graphs tend to be large, calling into doubt whether results from smaller benchmarks are informative. It is also not straightforward to adopt existing biomedical knowledge graphs such as Bio2RDF (\cite{dumontier2014bio2rdf}) as benchmark datasets, since they contain a large number of metadata relations that can interfere with the performance of link prediction algorithms, and special care needs to be taken to exclude trivially inferable statements from the test set.
A dedicated, high-quality and highly challenging benchmark optimized for the task of evaluating link prediction methods in large biomedical knowledge bases has not yet been established. In this paper, we introduce the OpenBioLink suite of software, datasets and benchmarks to close this gap.”

We now also explicitly refer to HetioNet in the Discussion and Future Work section:

“Future iterations of the benchmark dataset will be extended with additional knowledge from external resources such as Hetionet (\cite{Himmelstein_Baranzini_2015}).”

(Note: The motivation for not including Hetionet directly at the outset of the project was to have a more fine-grained access and configurability during benchmark creation as part of the OpenBioLink toolset, including negative example generation etc.)

**Closed** 2020-02-20 08:21 UTC
